apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: fastapi-app
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  PORT: "8000"
  DATABASE_URL: "postgresql+psycopg2://postgres:password123@postgres-service:5432/fastapi"
