apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
  namespace: fastapi-app
type: Opaque
stringData:
  POSTGRES_PASSWORD: "password123"
  SECRET_KEY: "7e9f78792102ff35b0243c694c5602807618e85c96e8e8c37c2e0940aa3700c4"
  ENCRYPTION_KEY: "Jr364QnDUZYS3xYw4sjVGB_J0a0xHXCx8F6f99R-5UU="
